name: Build MorningCoffee

on:
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake ninja-build patchelf file wget curl git \
            python3 python3-pip libglu1-mesa-dev mesa-utils libxcb-cursor0

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.5.0
          host: linux
          target: desktop

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH="$Qt6_DIR" -DCMAKE_BUILD_TYPE=Release
          cmake --build . --parallel

      - name: Download and extract linuxdeployqt
        run: |
          wget -O linuxdeployqt.AppImage https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod +x linuxdeployqt.AppImage
          ./linuxdeployqt.AppImage --appimage-extract
          mv squashfs-root linuxdeployqt-dir

      - name: Bundle with linuxdeployqt
        run: |
          mkdir -p package/MorningCoffee
          cp build/MorningCoffee package/MorningCoffee/
          chmod +x package/MorningCoffee/MorningCoffee

          # Minimal .desktop file is required
          cat > package/MorningCoffee/MorningCoffee.desktop << EOF
          [Desktop Entry]
          Type=Application
          Name=MorningCoffee
          Exec=MorningCoffee
          Icon=MorningCoffee
          Categories=Utility;
          EOF

          ./linuxdeployqt-dir/AppRun package/MorningCoffee/MorningCoffee.desktop -bundle-non-qt-libs

      - name: Upload artifact (folder)
        uses: actions/upload-artifact@v4
        with:
          name: MorningCoffee-linux
          path: package/**


  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.5.0
          host: windows
          target: desktop

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH="%Qt6_DIR%"
          cmake --build . --config Release

      - name: Deploy Qt DLLs
        run: |
          windeployqt build/Release/MorningCoffee.exe --no-translations --release

      - uses: actions/upload-artifact@v4
        with:
          name: MorningCoffee-windows
          path: build/Release/*